# Generated by Django 4.2.15 on 2025-01-02 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blend_Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_type', models.CharField(choices=[('Blend', 'Blend'), ('Bottling', 'Bottling')], default='Blend_bom_type', max_length=20)),
                ('bom_number', models.CharField(max_length=30)),
                ('bom_date', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_brand', to='masters.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_creator', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_sku', to='masters.sku')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_transaction_type', to='masters.transaction_type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_unit', to='masters.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Bom_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.blend_bom')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_item', to='masters.item')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_uom', to='masters.unit_of_measurement')),
            ],
        ),
    ]
