# Generated by Django 4.2.15 on 2025-01-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_gst_on_goods_options_and_more'),
        ('stock', '0002_blend_material_requisition_stock_entry_stock_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend_bom',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_sku', to='masters.sku'),
        ),
    ]
