# Generated by Django 4.2.15 on 2025-01-11 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_gst_on_goods_options_and_more'),
        ('stock', '0003_alter_blend_bom_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_ledger',
            old_name='average_rate',
            new_name='closing_rate',
        ),
        migrations.AddField(
            model_name='stock_ledger',
            name='issue_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0.0, 'Issue Quanytity can not be less than 0')]),
        ),
        migrations.AddField(
            model_name='stock_ledger',
            name='issue_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0, 'Issue Rate can not be less than 0')]),
        ),
        migrations.AddField(
            model_name='stock_ledger',
            name='issue_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0, 'Issue value can not be less than 0')]),
        ),
        migrations.AddField(
            model_name='stock_ledger',
            name='opening_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0, 'Opening Rate can not be less than 0')]),
        ),
        migrations.AddField(
            model_name='stock_ledger',
            name='receipt_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0.0, 'Transaction Quanytity can not be less than 0')]),
        ),
        migrations.AddField(
            model_name='stock_ledger',
            name='receipt_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0, 'Transaction Rate can not be less than 0')]),
        ),
        migrations.AddField(
            model_name='stock_ledger',
            name='receipt_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0, 'Transaction value can not be less than 0')]),
        ),
        migrations.AddField(
            model_name='stock_ledger',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock_ledger',
            name='transaction_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stock_ledger',
            name='transaction_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_transaction_type', to='masters.transaction_type'),
        ),
        migrations.AlterField(
            model_name='stock_ledger',
            name='closing_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0.0, 'Opening Quanytity can not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='stock_ledger',
            name='opening_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0.0, 'Opening Quanytity can not be less than 0')]),
        ),
    ]
