# Generated by Django 4.2.15 on 2025-01-12 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_gst_on_goods_options_and_more'),
        ('stock', '0004_rename_average_rate_stock_ledger_closing_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_ledger',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_unit', to='masters.unit'),
            preserve_default=False,
        ),
    ]
