# Generated by Django 4.2.15 on 2025-01-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_ledger_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_requisition',
            name='issue_slip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stock_entry'),
        ),
        migrations.AlterField(
            model_name='blend',
            name='batch_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Batch Quantity in Cases'),
        ),
    ]
