# Generated by Django 4.2.15 on 2025-01-12 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_gst_on_goods_options_and_more'),
        ('stock', '0006_material_requisition_issue_slip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_entry',
            name='issue_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Issue Quanity can not be less than 0')]),
        ),
        migrations.AddField(
            model_name='stock_entry',
            name='issue_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='stock_entry',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entry_to_location', to='masters.unit_sub_location'),
        ),
        migrations.AlterField(
            model_name='stock_entry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0, 'Reciept Quanity can not be less than 0')]),
        ),
    ]
