# Generated by Django 4.2.15 on 2025-01-18 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stock_entry_issue_quantity_stock_entry_issue_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_ledger',
            name='closing_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0.0, 'Opening Quantity can not be less than 0')]),
        ),
    ]
