# Generated by Django 4.2.15 on 2025-02-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stock_entry_return_quantity_stock_entry_return_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend_bom',
            name='bom_type',
            field=models.CharField(choices=[('Blend', 'Blend'), ('Bottling', 'Bottling')], default='Blend', max_length=20),
        ),
    ]
