# Generated by Django 4.2.15 on 2025-02-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_blend_bom_bom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom_items',
            name='bom_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
