# Generated by Django 4.2.15 on 2025-02-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_stock_ledger_stock_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_entry',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.blend_bom'),
        ),
    ]
