# Generated by Django 4.2.15 on 2025-02-23 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_stock_entry_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_entry',
            name='consumption_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0, 'Return Quanity can not be less than 0')]),
        ),
        migrations.AddField(
            model_name='stock_entry',
            name='consumption_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
