# Generated by Django 4.2.15 on 2025-03-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_stock_entry_consumption_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_requisition',
            name='required_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
