# Generated by Django 4.2.15 on 2025-06-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_alter_material_requisition_required_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_entry',
            name='account_entry',
            field=models.BooleanField(default=False),
        ),
    ]
