# Generated by Django 4.2.15 on 2025-01-02 18:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(default='', max_length=200)),
                ('user_type', models.CharField(choices=[('Transporter', 'Transporter'), ('Service_Provider', 'Service_Provider'), ('Admin', 'Admin'), ('Employee', 'Employee'), ('Goods_Supplier', 'Goods_Supplier')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_class', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('pin', models.CharField(default='', max_length=6)),
                ('pan_no', models.CharField(default='', max_length=10)),
                ('tan_no', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('conversion_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(max_length=8)),
                ('item_name', models.CharField(max_length=200)),
                ('item_tax_type', models.CharField(choices=[('Non_GST', 'Non_GST'), ('GST', 'GST')], default='GST', max_length=50)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.account_chart')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac_code', models.CharField(max_length=6)),
                ('service_name', models.CharField(max_length=50)),
                ('nature_of_supply', models.CharField(choices=[('Intra_State', 'Intra-State'), ('Inter_State', 'Inter_State')], default='Inter_State', max_length=30)),
                ('service_type', models.CharField(choices=[('Specified', 'Specified'), ('Non-Specified', 'Non-Specified')], default='Non-Specified', max_length=30)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('FCM', 'FCM'), ('RCM', 'RCM')], default='FCM', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spirit_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spirit_class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State_Excise_levies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=255)),
                ('capacity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('opening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('opening_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('receipt_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('receipt_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('issue_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('closing_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('closing_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.item')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('assessee_type', models.CharField(choices=[('Individual', 'Individual'), ('HEF', 'HUF'), ('Partnership', 'Partnership'), ('Company', 'Company'), ('LLP', 'LLP'), ('Trust', 'Trust'), ('Other', 'Other')], default='', max_length=50)),
                ('location', models.CharField(choices=[('India', 'India'), ('Overseas', 'Overseas')], default='India', max_length=20)),
                ('related', models.BooleanField(default=False)),
                ('gstin', models.CharField(default='', max_length=15)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.account_chart')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.currency')),
                ('supplier_state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.state')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=200)),
                ('address', models.TextField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('unit_type', models.CharField(choices=[('Factory', 'Factory'), ('Region_Office', 'Region_Office'), ('Zonal_Office', 'Zonal_Office'), ('HeadOffice', 'HeadOffice')], max_length=100)),
                ('gstin', models.CharField(max_length=15)),
                ('vat_no', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('landphone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.company')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='masters.state')),
            ],
        ),
        migrations.CreateModel(
            name='Unit_of_Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Stock_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_stock_location', models.CharField(max_length=255)),
                ('capacity', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('opening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('opening_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('receipt_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('receipt_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('issue_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('closing_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('closing_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('average_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.item')),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='masters.stock_location')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Unit_of_Measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='masters.unit_of_measurement')),
            ],
        ),
        migrations.CreateModel(
            name='User_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sale', 'Sale'), ('Supply_Chain', 'Supply_Chain'), ('Procurement', 'Procurement'), ('Store', 'Store'), ('Quality_Control', 'Quality_Control'), ('Security', 'Security'), ('Manufactruing', 'Manufacturing')], max_length=100)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Sub_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_loc_name', models.CharField(max_length=255)),
                ('capacity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('opening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('opening_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('receipt_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('receipt_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('issue_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('closing_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('closing_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('average_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.item')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
                ('unit_stock_location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='masters.unit_stock_location')),
            ],
        ),
        migrations.CreateModel(
            name='TDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('classification', models.CharField(default='', max_length=100)),
                ('deductee_type', models.CharField(choices=[('Individual', 'Individual'), ('HEF', 'HUF'), ('Partnership', 'Partnership'), ('Company', 'Company'), ('LLP', 'LLP'), ('Trust', 'Trust'), ('Other', 'Other')], max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_classification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.service')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levy_mode', models.CharField(choices=[('FCM', 'FCM'), ('RCM', 'RCM')], max_length=20)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.service')),
                ('supplier', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='masters.supplier')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('is_msme', models.BooleanField(default=False)),
                ('zip', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_supplier', to='masters.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_user', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.state')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_unit', to='masters.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_suppliers', to='masters.unit'),
        ),
        migrations.CreateModel(
            name='State_Tax_on_Sale_Of_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('creditable', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_account', to='masters.account_chart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_item', to='masters.item')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_tax', to='masters.state')),
            ],
        ),
        migrations.CreateModel(
            name='State_Excise_taxes_On_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidence', models.CharField(choices=[('Inward', 'Inward'), ('Outward', 'Outward')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excise_account', to='masters.account_chart')),
                ('levy_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levy_unit', to='masters.unit_of_measurement')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_excise', to='masters.state')),
                ('tax_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exicse_levies', to='masters.state_excise_levies')),
            ],
        ),
        migrations.CreateModel(
            name='Standard_Quality_Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('standard_value', models.CharField(max_length=20)),
                ('item_cat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='masters.item_category')),
                ('uom', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.unit_of_measurement')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.company')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='masters.unit_of_measurement', verbose_name='Unit of Measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivarable_name', models.CharField(max_length=50)),
                ('basis', models.CharField(choices=[('Per_Day', 'Per_Day'), ('Per-Consignment', 'Per_Consignment'), ('Lump_Sum', 'Lump_Sum')], default='Per_Consignment', max_length=30)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.supplier_service')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Lower_TDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(default='', max_length=100)),
                ('sub_classification', models.CharField(default='', max_length=100)),
                ('deductee_type', models.CharField(choices=[('Individual', 'Individual'), ('HUF', 'HUF'), ('Partnership', 'Partnership'), ('Company', 'Company'), ('LLP', 'LLP'), ('Trust', 'Trust'), ('Other', 'Other')], default='', max_length=50)),
                ('lower_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='media')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.tds')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.item_category'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.item_class'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.unit_of_measurement'),
        ),
        migrations.CreateModel(
            name='Gst_On_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_gst_account', to='masters.account_chart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_item', to='masters.item')),
            ],
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('air', 'Air'), ('sea', 'Sea'), ('road', 'Road'), ('rail', 'Rail'), ('courier', 'Courier')], max_length=50)),
                ('origin_city', models.CharField(max_length=100)),
                ('destinaton_city', models.CharField(max_length=100)),
                ('dumerages_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dumerage Rate Per Day')),
                ('toll_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgst_account', to='masters.account_chart')),
                ('igst_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='igst_account', to='masters.account_chart')),
                ('provision_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provision', to='masters.account_chart')),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transporter_service', to='masters.supplier_service')),
                ('sgst_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgst_account', to='masters.account_chart')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_supplier', to='masters.supplier')),
                ('tds_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_account', to='masters.account_chart')),
                ('transporter_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporter', to='masters.account_chart')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='freights', to='masters.unit')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freights', to='masters.vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='DOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('monetary_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.transaction_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.CharField(max_length=8)),
                ('tax_name', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_account', to='masters.account_chart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_item', to='masters.item')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='masters.state'),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle', models.FloatField()),
                ('bl', models.FloatField()),
                ('pl', models.FloatField()),
                ('al', models.FloatField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.sku')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.company')),
                ('finished_goods_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_finished_goods_account', to='masters.account_chart', verbose_name='Finished Goods Accout')),
                ('spirit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='masters.spirit_class', verbose_name='Class')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='masters.brand_variant')),
                ('wip_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_wip_account', to='masters.account_chart', verbose_name='Stock at Bottling Tank Shop Floor')),
                ('wip_blend_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_wip_blend_account', to='masters.account_chart', verbose_name='Process Stock in Proceesing Tank')),
                ('wip_finished_blend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_wip_finished_blend_account', to='masters.account_chart', verbose_name='Finished_Blend in Holding Tank')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Sub_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_class', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('account_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.account_class')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.account_category')),
            ],
        ),
        migrations.AddField(
            model_name='account_chart',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.account_sub_category'),
        ),
        migrations.AddField(
            model_name='account_category',
            name='sub_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.account_sub_class'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='masters.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Landed_Cost_Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misc_costs', models.DecimalField(decimal_places=2, default=0, help_text='Pls insert per unit  value same wiil be picked to calculate landed cost', max_digits=10)),
                ('clearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.supplier_service')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcr_item', to='masters.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcr_supplier', to='masters.supplier')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
            options={
                'verbose_name_plural': 'Landed Cost Rule',
                'indexes': [models.Index(fields=['id'], name='masters_lan_id_896da6_idx')],
                'unique_together': {('unit', 'item', 'supplier')},
            },
        ),
    ]
