# Generated by Django 4.2.15 on 2025-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_chart',
            name='account_code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
