# Generated by Django 4.2.15 on 2025-01-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_account_chart_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_chart',
            name='account_code',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
    ]
