# Generated by Django 4.2.15 on 2025-01-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_account_chart_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles',
            name='department',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sale', 'Sale'), ('Supply_Chain', 'Supply_Chain'), ('Procurement', 'Procurement'), ('Store', 'Store'), ('Quality_Control', 'Quality_Control'), ('Security', 'Security'), ('Manufacturing', 'Manufacturing')], max_length=100),
        ),
    ]
