# Generated by Django 4.2.15 on 2025-01-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_rename_wip_finished_blend_brand_finished_blend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='finished_blend',
            new_name='finished_blend_account',
        ),
    ]
