# Generated by Django 4.2.15 on 2025-01-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_rename_finished_blend_brand_finished_blend_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_item', to='masters.item'),
        ),
    ]
