# Generated by Django 4.2.15 on 2025-01-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_brand_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='item',
        ),
    ]
