# Generated by Django 4.2.15 on 2025-01-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_remove_brand_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='finished_blend_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_finished_blend_item', to='masters.item', verbose_name='Finished Blend Item'),
        ),
        migrations.AddField(
            model_name='brand',
            name='finished_goods_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_finished_goods_item', to='masters.item', verbose_name='Finished Goods Item'),
        ),
        migrations.AddField(
            model_name='brand',
            name='wip_blend_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_wip_blend_item', to='masters.item', verbose_name='WIP Blend Item'),
        ),
    ]
