# Generated by Django 4.2.15 on 2025-03-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_created_by', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
        migrations.CreateModel(
            name='State_Excise_Levies_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levy_rate', models.FloatField(blank=True, null=True)),
                ('levy_formula', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slab', models.CharField(choices=[('formula', 'formula'), ('slab', 'slab')], default='', max_length=255)),
                ('payee', models.CharField(choices=[('Company', 'Company'), ('Wholesale', 'Wholesale'), ('Retailer', 'Retailer')], default='Company', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levy_created_by', to=settings.AUTH_USER_MODEL)),
                ('levy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_levy_name', to='masters.state_excise_levies')),
                ('levy_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.unit_of_measurement')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levy_state', to='masters.state')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15)),
                ('vat_no', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('tan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=6)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('kyc', models.FileField(blank=True, null=True, upload_to='media')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.customer')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.user_roles')),
            ],
        ),
    ]
