# Generated by Django 4.2.15 on 2025-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_customer_state_excise_levies_rate_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_excise_levies_rate',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state_excise_levies_rate',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
