# Generated by Django 4.2.15 on 2025-03-14 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_state_excise_levies_rate_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='valid_from',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='valid_till',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
