# Generated by Django 4.2.15 on 2025-03-14 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_alter_state_excise_levies_rate_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='valid_from',
            field=models.DateField(default=datetime.datetime.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='valid_till',
            field=models.DateField(default=datetime.datetime.today),
            preserve_default=False,
        ),
    ]
