# Generated by Django 4.2.15 on 2025-03-14 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_alter_state_excise_levies_rate_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state_excise_levies_rate',
            name='updated',
        ),
        migrations.AddField(
            model_name='state_excise_levies_rate',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='levy_formula',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='levy_rate',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='levy_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='state_levy_unit', to='masters.unit_of_measurement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='payee',
            field=models.CharField(choices=[('Company', 'Company'), ('Wholesale', 'Wholesale'), ('Retailer', 'Retailer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='slab',
            field=models.CharField(choices=[('formula', 'formula'), ('slab', 'slab')], max_length=255),
        ),
    ]
