# Generated by Django 4.2.15 on 2025-03-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_remove_state_excise_levies_rate_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='state_excise_levies_rate',
            name='levy_formula',
        ),
        migrations.AlterField(
            model_name='state_excise_levies_rate',
            name='levy_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
