# Generated by Django 4.2.15 on 2025-03-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_formula_remove_state_excise_levies_rate_levy_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_excise_levies_rate',
            name='levy_formula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levy_formula', to='masters.formula'),
            preserve_default=False,
        ),
    ]
