# Generated by Django 4.2.15 on 2025-03-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_state_excise_levies_rate_levy_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_excise_levies_rate',
            name='levy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
