# Generated by Django 4.2.15 on 2025-03-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0018_state_excise_levies_rate_levy_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='formula',
            field=models.CharField(max_length=200),
        ),
    ]
