# Generated by Django 4.2.15 on 2025-03-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0019_alter_formula_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_excise_levies',
            name='tax_name',
            field=models.CharField(max_length=100),
        ),
    ]
