# Generated by Django 4.2.15 on 2025-03-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0020_alter_state_excise_levies_tax_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='cost_card_head',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formula',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='state_fromula', to='masters.state'),
            preserve_default=False,
        ),
    ]
