# Generated by Django 4.2.15 on 2025-03-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_formula_cost_card_head_formula_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='cost_card_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_cost_card_head', to='masters.state_excise_levies'),
        ),
    ]
