# Generated by Django 4.2.15 on 2025-03-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0023_remove_formula_cost_card_head_remove_formula_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal_name', models.CharField(max_length=255)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtotal_formula', to='masters.formula')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtotal_state', to='masters.state')),
            ],
        ),
    ]
