# Generated by Django 4.2.15 on 2025-03-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_subtotal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtotal',
        ),
    ]
