# Generated by Django 4.2.15 on 2025-03-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_delete_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to='masters.account_chart'),
            preserve_default=False,
        ),
    ]
