# Generated by Django 4.2.15 on 2025-03-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_customer_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_excise_levies_rate',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_of_excise_levy', to='masters.account_chart'),
            preserve_default=False,
        ),
    ]
