# Generated by Django 4.2.15 on 2025-03-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0027_state_excise_levies_rate_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCS_Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tcs_head', to='masters.tcs_head')),
                ('transaction_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tcs_transaction_type', to='masters.transaction_type')),
            ],
        ),
    ]
