# Generated by Django 4.2.15 on 2025-03-30 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_tcs_head_tcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_type',
            name='Unit_of_Measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_uom', to='masters.unit_of_measurement'),
        ),
    ]
