# Generated by Django 4.2.15 on 2025-04-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_alter_vehicle_type_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles',
            name='department',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sale', 'Sale'), ('Supply_Chain', 'Supply_Chain'), ('Procurement', 'Procurement'), ('Store', 'Store'), ('Quality_Control', 'Quality_Control'), ('Security', 'Security'), ('Dispatch', 'Dispatch'), ('Manufacturing', 'Manufacturing')], max_length=100),
        ),
    ]
