# Generated by Django 4.2.15 on 2025-04-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_alter_user_roles_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='unit',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_item', to='masters.item'),
        ),
    ]
