# Generated by Django 4.2.15 on 2025-04-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_alter_supplier_supplier_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
