# Generated by Django 4.2.15 on 2025-04-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0033_currency_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('year_type', models.CharField(choices=[('financial', 'Financial Year'), ('reporting', 'Reporting Year')], default='financial', max_length=20)),
            ],
            options={
                'unique_together': {('start_date', 'end_date', 'year_type')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.account_chart')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.accountingyear')),
            ],
            options={
                'unique_together': {('account_chart', 'unit', 'year')},
            },
        ),
    ]
