# Generated by Django 4.2.15 on 2025-04-14 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0034_accountingyear_city_unitaccountbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitaccountbalance',
            name='closing_balance_date',
            field=models.DateField(default=datetime.date(2000, 3, 31)),
        ),
        migrations.AddField(
            model_name='unitaccountbalance',
            name='opening_balance_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
