# Generated by Django 4.2.15 on 2025-04-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0035_unitaccountbalance_closing_balance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='nature_of_supply',
        ),
    ]
