# Generated by Django 4.2.15 on 2025-04-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0036_remove_service_nature_of_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
    ]
