# Generated by Django 4.2.15 on 2025-04-27 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0037_alter_service_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_account', to='masters.account_chart'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cost_Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_center_created_by', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
    ]
