# Generated by Django 4.2.15 on 2025-05-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0038_service_account_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='masters.account_chart'),
        ),
    ]
