# Generated by Django 4.2.15 on 2025-05-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0040_sub_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_profile',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.currency'),
        ),
    ]
