# Generated by Django 4.2.15 on 2025-05-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0042_doa_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doa',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doa_cost_center', to='masters.sub_cost_center'),
        ),
    ]
