# Generated by Django 4.2.15 on 2025-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0043_alter_doa_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles',
            name='department',
            field=models.CharField(choices=[('Finance', (('Finance_Control', 'Finance_Control'), ('Finance_Tax', 'Finance_Tax'))), ('Marketing', 'Marketing'), ('Sale', 'Sale'), ('Supply_Chain', 'Supply_Chain'), ('Procurement', 'Procurement'), ('Store', 'Store'), ('Quality_Control', 'Quality_Control'), ('Security', 'Security'), ('Dispatch', 'Dispatch'), ('Manufacturing', 'Manufacturing')], max_length=100),
        ),
    ]
