# Generated by Django 4.2.15 on 2025-05-15 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0045_service_category_service_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_sub_category', to='masters.service_sub_category', verbose_name='Service Sub Category'),
            preserve_default=False,
        ),
    ]
