# Generated by Django 4.2.15 on 2025-05-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0046_service_service_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_profile',
            name='cost_center',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='supllier_user_department', to='masters.sub_cost_center', verbose_name='User Department'),
            preserve_default=False,
        ),
    ]
