# Generated by Django 4.2.15 on 2025-06-01 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0047_supplier_profile_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lower_tds',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
