# Generated by Django 4.2.15 on 2025-06-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0049_supplier_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Invoice_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_number', models.CharField(max_length=50)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('matching_status', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tcs_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoice_status', to='masters.supplier')),
            ],
        ),
    ]
