# Generated by Django 4.2.15 on 2025-06-24 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0050_supplier_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_transporter', to='masters.supplier'),
        ),
    ]
