# Generated by Django 4.2.15 on 2025-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0051_freight_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_profile',
            name='is_sez',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier_profile',
            name='supply_type',
            field=models.CharField(choices=[('Goods', 'Goods'), ('Service', 'Service')], default='Goods', help_text='Goods or Service', max_length=50),
        ),
    ]
