# Generated by Django 4.2.15 on 2025-07-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0053_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='credit_terms',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
