# Generated by Django 4.2.15 on 2025-01-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_gst_on_goods_options_and_more'),
        ('stock', '0009_stock_entry_return_quantity_stock_entry_return_value'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend_wip',
            name='blend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blend_wip_blend', to='stock.blend'),
        ),
        migrations.AlterField(
            model_name='blend_wip',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blend_wip_issue', to='stock.stock_entry'),
        ),
        migrations.AlterField(
            model_name='blend_wip',
            name='stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blend_wip_storage_location', to='masters.unit_sub_location'),
        ),
        migrations.AlterField(
            model_name='blend_wip',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blend_wip_to_location', to='masters.unit_sub_location', verbose_name='Issue To Location'),
        ),
        migrations.AlterField(
            model_name='blend_wip',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blend_wip_transaction_type', to='masters.transaction_type'),
        ),
        migrations.AlterField(
            model_name='blend_wip',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blend_wip_unit', to='masters.unit'),
        ),
    ]
