# Generated by Django 4.2.15 on 2025-01-26 17:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stock_entry_return_quantity_stock_entry_return_value'),
        ('masters', '0007_rename_finished_blend_brand_finished_blend_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_alter_blend_wip_blend_alter_blend_wip_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_Blend_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=30)),
                ('transaction_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Quantity Transferred')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('blend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_blend', to='stock.blend')),
                ('blend_wip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_number', to='production.blend_wip')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finish_blend', to=settings.AUTH_USER_MODEL)),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blend_location', to='masters.unit_sub_location')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='masters.unit_sub_location')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.transaction_type')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
    ]
