# Generated by Django 4.2.15 on 2025-01-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
        ('production', '0004_finished_blend_transaction_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_blend_stock_ledger',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_blend_item', to='masters.item'),
        ),
        migrations.AlterField(
            model_name='finished_blend_transaction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blend_item_transaction', to='masters.item'),
        ),
    ]
