# Generated by Django 4.2.15 on 2025-01-28 16:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0009_stock_entry_return_quantity_stock_entry_return_value'),
        ('production', '0005_finished_blend_stock_ledger_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottling_lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(max_length=50)),
                ('line_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('line_type', models.CharField(choices=[('Mannual', 'Mannual'), ('Automatic', 'Automatic'), ('Semi-Auto', 'Semi-Auto')], max_length=50)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottling_line_unit', to='masters.unit_of_measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Production_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=30)),
                ('transaction_date', models.DateField()),
                ('production', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Production in Bottles')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_production_plan_brand', to='masters.brand')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_production_plan_line', to='production.bottling_lines')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_production_plan_sku', to='masters.sku')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.transaction_type')),
            ],
        ),
        migrations.CreateModel(
            name='Blend_Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=30)),
                ('transaction_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Quantity To be manufactured in Bottles')),
                ('blend_required', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('blend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requistion_blend', to='stock.blend')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitioned_blend', to='masters.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_by', to=settings.AUTH_USER_MODEL)),
                ('finish_blend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_fb_number', to='production.finished_blend_transaction')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requistioned_sku', to='masters.sku')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_blend_location', to='masters.unit_sub_location')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.transaction_type')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.unit_of_measurement')),
            ],
        ),
    ]
