# Generated by Django 4.2.15 on 2025-01-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_bottling_lines_daily_production_plan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blend_Requisition',
        ),
    ]
