# Generated by Django 4.2.15 on 2025-01-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
        ('production', '0008_daily_production_plan_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_production_plan',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.state'),
        ),
    ]
