# Generated by Django 4.2.15 on 2025-02-04 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
        ('production', '0009_daily_production_plan_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blend_Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=30)),
                ('transaction_date', models.DateField()),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_by', to=settings.AUTH_USER_MODEL)),
                ('finish_blend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blend_requistion_finish_blend', to='production.finished_blend_transaction')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blend_requisition_plan', to='production.daily_production_plan')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.transaction_type')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
    ]
