# Generated by Django 4.2.15 on 2025-02-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
        ('production', '0010_blend_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='blend_requisition',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Blend_requisition_item', to='masters.item'),
        ),
        migrations.AddField(
            model_name='blend_requisition',
            name='required_qunatity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='blend_requisition',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blend_requisition_uom', to='masters.unit_of_measurement'),
        ),
    ]
