# Generated by Django 4.2.15 on 2025-02-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_rename_required_qunatity_blend_requisition_required_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend_requisition',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blend_requisition_plan', to='production.daily_production_plan'),
        ),
    ]
