# Generated by Django 4.2.15 on 2025-02-09 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_blend_bom_bom_type'),
        ('production', '0014_blend_requisition_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_production_plan',
            name='blend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_production_plan_blend', to='stock.blend'),
        ),
    ]
