# Generated by Django 4.2.15 on 2025-02-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_daily_production_plan_blend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_production_plan',
            name='production',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Production in Cases'),
        ),
    ]
