# Generated by Django 4.2.15 on 2025-02-20 15:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
        ('stock', '0013_alter_stock_ledger_stock_entry'),
        ('production', '0016_alter_daily_production_plan_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=30)),
                ('transaction_date', models.DateTimeField()),
                ('created', models.DateField()),
                ('modified', models.DateField()),
                ('blend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.blend')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_created_by', to=settings.AUTH_USER_MODEL)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_transaction', to='masters.transaction_type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_unit_name', to='masters.unit')),
            ],
        ),
        migrations.RemoveField(
            model_name='blend_requisition',
            name='finish_blend',
        ),
        migrations.CreateModel(
            name='Map_FG_Brand_SKU_Stock_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_stock_location', to='masters.brand')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_sku_location', to='masters.unit_sub_location')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_stock_location', to='masters.sku')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Goods_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0, message='Opening Quantity cannot be less than zero')])),
                ('opening_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0, message='Opening value cannot be less than zero')])),
                ('production_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0, message='Production Quantity cannot be less than zero')])),
                ('production_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0, message='Production value cannot be less than zero')])),
                ('despatch_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0, message='Despatch Quantity cannot be less than zero')])),
                ('despatch_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0, message='Despatch Value cannot be less than zero')])),
                ('closing_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0, message='Closing Quantity cannot be less than zero')])),
                ('closing_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0, message='Closing Quantity cannot be less than zero')])),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0, message='Average Cost cannot be less than zero')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_Account', to='masters.account_chart')),
                ('blend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.blend')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_brand', to='masters.brand')),
                ('finished_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_id', to='production.finished_goods')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.map_fg_brand_sku_stock_location')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_sku', to='masters.sku')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_state', to='masters.state')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
    ]
