# Generated by Django 4.2.15 on 2025-02-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_finished_goods_remove_blend_requisition_finish_blend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished_goods_items',
            name='account',
        ),
        migrations.RemoveField(
            model_name='finished_goods_items',
            name='blend',
        ),
        migrations.RemoveField(
            model_name='finished_goods_items',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='finished_goods_items',
            name='finished_goods',
        ),
        migrations.RemoveField(
            model_name='finished_goods_items',
            name='location',
        ),
        migrations.RemoveField(
            model_name='finished_goods_items',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='finished_goods_items',
            name='state',
        ),
        migrations.RemoveField(
            model_name='finished_goods_items',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='map_fg_brand_sku_stock_location',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='map_fg_brand_sku_stock_location',
            name='location',
        ),
        migrations.RemoveField(
            model_name='map_fg_brand_sku_stock_location',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='map_fg_brand_sku_stock_location',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Finished_Goods',
        ),
        migrations.DeleteModel(
            name='Finished_Goods_Items',
        ),
        migrations.DeleteModel(
            name='Map_FG_Brand_SKU_Stock_location',
        ),
    ]
