# Generated by Django 4.2.15 on 2025-02-20 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_production_report_production_overheads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_report',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_report_plan', to='production.daily_production_plan'),
        ),
    ]
