# Generated by Django 4.2.15 on 2025-02-22 11:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
        ('stock', '0013_alter_stock_ledger_stock_entry'),
        ('production', '0020_production_report_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_Plan_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Production in Cases')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_production_plan_brand', to='masters.brand')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_production_plan_line', to='production.bottling_lines')),
            ],
        ),
        migrations.CreateModel(
            name='Production_Report_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Production in Cases')),
                ('production_value', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_report_blend', to='stock.blend')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_report_brand', to='masters.brand')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_report_item', to='masters.item')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_report_line', to='production.bottling_lines')),
            ],
        ),
        migrations.RemoveField(
            model_name='blend_consumption',
            name='consumption_quantity',
        ),
        migrations.RemoveField(
            model_name='blend_consumption',
            name='consumption_value',
        ),
        migrations.RemoveField(
            model_name='blend_consumption',
            name='opening_quantity',
        ),
        migrations.RemoveField(
            model_name='daily_production_plan',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='daily_production_plan',
            name='line',
        ),
        migrations.RemoveField(
            model_name='daily_production_plan',
            name='production',
        ),
        migrations.RemoveField(
            model_name='daily_production_plan',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='daily_production_plan',
            name='state',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='average_cost',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='blend',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='item',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='line',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='production',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='production_value',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='state',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='unit',
        ),
        migrations.AddField(
            model_name='blend_consumption',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blend_consumption_item', to='masters.item'),
        ),
        migrations.DeleteModel(
            name='Blend_Requisition',
        ),
        migrations.AddField(
            model_name='production_report_line',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_report_line', to='production.production_report'),
        ),
        migrations.AddField(
            model_name='production_report_line',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_report_sku', to='masters.sku'),
        ),
        migrations.AddField(
            model_name='production_report_line',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.state'),
        ),
        migrations.AddField(
            model_name='production_report_line',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_report_unit', to='masters.unit'),
        ),
        migrations.AddField(
            model_name='production_plan_line',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plan_line', to='production.daily_production_plan'),
        ),
        migrations.AddField(
            model_name='production_plan_line',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_production_plan_sku', to='masters.sku'),
        ),
        migrations.AddField(
            model_name='production_plan_line',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.state'),
        ),
    ]
