# Generated by Django 4.2.15 on 2025-02-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_production_plan_line_production_report_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dg_consumption',
            name='blend',
        ),
        migrations.RemoveField(
            model_name='dg_consumption',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dg_consumption',
            name='daily_report',
        ),
        migrations.RemoveField(
            model_name='dg_consumption',
            name='issue_quantity',
        ),
        migrations.RemoveField(
            model_name='dg_consumption',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='dg_consumption',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='production_overheads',
            name='expense_head',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='production_report',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='production_report_line',
            name='blend',
        ),
        migrations.RemoveField(
            model_name='production_report_line',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='production_report_line',
            name='item',
        ),
        migrations.RemoveField(
            model_name='production_report_line',
            name='line',
        ),
        migrations.RemoveField(
            model_name='production_report_line',
            name='report',
        ),
        migrations.RemoveField(
            model_name='production_report_line',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='production_report_line',
            name='state',
        ),
        migrations.RemoveField(
            model_name='production_report_line',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Blend_Consumption',
        ),
        migrations.DeleteModel(
            name='Dg_Consumption',
        ),
        migrations.DeleteModel(
            name='Production_Overheads',
        ),
        migrations.DeleteModel(
            name='Production_Report',
        ),
        migrations.DeleteModel(
            name='Production_Report_Line',
        ),
    ]
