# Generated by Django 4.2.15 on 2025-02-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_remove_dg_consumption_blend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished_blend_transaction',
            name='blend',
        ),
        migrations.RemoveField(
            model_name='finished_blend_transaction',
            name='blend_wip',
        ),
        migrations.RemoveField(
            model_name='finished_blend_transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='finished_blend_transaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='finished_blend_transaction',
            name='stock_location',
        ),
        migrations.RemoveField(
            model_name='finished_blend_transaction',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='finished_blend_transaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='finished_blend_transaction',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Finished_blend_Stock_Ledger',
        ),
        migrations.DeleteModel(
            name='Finished_Blend_Transaction',
        ),
    ]
