# Generated by Django 4.2.15 on 2025-02-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_remove_finished_blend_transaction_blend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_production_plan',
            name='bottled',
            field=models.BooleanField(default=False),
        ),
    ]
