# Generated by Django 4.2.15 on 2025-02-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
        ('stock', '0015_stock_entry_consumption_quantity_and_more'),
        ('production', '0026_map_brand_sku_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overheads_Absorbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('blend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.blend')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absorbed_overhead', to='accounts.overheads')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.unit_of_measurement')),
            ],
            options={
                'verbose_name_plural': 'Overheads Absorbed',
            },
        ),
    ]
