# Generated by Django 4.2.15 on 2025-02-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_map_brand_sku_item_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overheads_absorbed',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='overheads_absorbed',
            name='to_date',
        ),
        migrations.AddField(
            model_name='overheads_absorbed',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
