# Generated by Django 4.2.15 on 2025-02-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_stock_entry_consumption_quantity_and_more'),
        ('production', '0029_remove_overheads_absorbed_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overheads_absorbed',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='overheads_absorbed',
            name='blend',
        ),
        migrations.AddField(
            model_name='overheads_absorbed',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overheads_absorbed',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Blend_Overhead_Absorbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overhead_blend', to='stock.blend')),
                ('overhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overhead_name', to='production.overheads_absorbed')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_report', to='production.production_report')),
            ],
        ),
    ]
