# Generated by Django 4.2.15 on 2025-02-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
        ('production', '0030_remove_overheads_absorbed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blend_overhead_absorbed',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overhead_unit', to='masters.unit'),
        ),
    ]
