# Generated by Django 4.2.15 on 2025-02-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_brand_finished_blend_item_brand_finished_goods_item_and_more'),
        ('production', '0031_blend_overhead_absorbed_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blend_overhead_absorbed',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blend_overhead_absorbed',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blend_overhead_absorbed',
            name='transaction_type',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='blend_overhead_absorbed_transaction_type', to='masters.transaction_type'),
        ),
    ]
