# Generated by Django 4.2.15 on 2025-03-30 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_tcs_head_tcs'),
        ('production', '0036_map_brand_sku_item_sale_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_brand_sku_item',
            name='cost_of_sale_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_cost_of_sale_account', to='masters.account_chart'),
        ),
    ]
