# Generated by Django 4.2.15 on 2025-01-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inv_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(editable=False, max_length=100)),
                ('transaction_cat', models.CharField(blank=True, choices=[('Select', 'Select'), ('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50, null=True)),
                ('transaction_date', models.DateField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Overheads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Overhead_Name')),
                ('type', models.CharField(choices=[('Production_Overheads', 'Production_Overheads'), ('Admin_OVerheads', 'Admin_Overheads'), ('Sales_Overheads', 'Sales_Overheads'), ('Marketing_Overhead', 'Marketing_Overheads'), ('Distribution_Overheads', 'Distribution_Overheads')], max_length=100, verbose_name='Overhead_Type')),
                ('category', models.CharField(choices=[('Fixed_Overheads', 'Fixed_Overheads'), ('Variable_Overheads', 'Variable_Overheads'), ('Budgeted_Overhead', 'Budgeted_Overheads')], max_length=50, verbose_name='Overhead_Category')),
            ],
            options={
                'verbose_name_plural': 'Overheads',
            },
        ),
    ]
