# Generated by Django 4.2.15 on 2025-01-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overheads',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.account_chart', verbose_name='Pls. Map the Overhead Account'),
        ),
        migrations.AddField(
            model_name='inv_transaction',
            name='account_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='masters.account_chart'),
        ),
        migrations.AddField(
            model_name='inv_transaction',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.transaction_type'),
        ),
        migrations.AddField(
            model_name='inv_transaction',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.unit'),
        ),
        migrations.AddIndex(
            model_name='inv_transaction',
            index=models.Index(fields=['id', 'unit'], name='accounts_in_id_a0c554_idx'),
        ),
    ]
