# Generated by Django 4.2.15 on 2025-04-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_alter_user_roles_department'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=50, unique=True)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('bank_payment', 'Bank Payment'), ('bank_receipt', 'Bank Receipt'), ('cash_payment', 'Cash Payment'), ('cash_receipt', 'Cash Receipt'), ('debit_note', 'Debit Note'), ('credit_note', 'Credit Note')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='inv_transaction',
            name='transaction_cat',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.account_chart')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.transaction')),
            ],
        ),
    ]
