# Generated by Django 4.2.15 on 2025-04-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_transaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionDetail',
        ),
    ]
