# Generated by Django 4.2.15 on 2025-07-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0053_bank'),
        ('accounts', '0004_delete_account_remove_transactiondetail_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.bank')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
        migrations.CreateModel(
            name='BankPaymentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='accounts.bankpaymentvoucher')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.supplier')),
            ],
        ),
    ]
