# Generated by Django 4.2.15 on 2025-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankpaymentvoucher_bankpaymentlineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpaymentlineitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
