# Generated by Django 4.2.15 on 2025-04-27 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0038_service_account_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=20, unique=True, verbose_name='Invoice Number')),
                ('transaction_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_invoice_approver', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_invoice_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=20, unique=True, verbose_name='Order Number')),
                ('transaction_date', models.DateField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_approver', to=settings.AUTH_USER_MODEL)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_cost_center', to='masters.cost_center')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=20, unique=True, verbose_name='Quotation Number')),
                ('transaction_date', models.DateField()),
                ('taxes', models.CharField(choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], default='Exclusive', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_approved_by', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_approver', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_created_by', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_service_supplier', to='masters.supplier')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_type', to='masters.transaction_type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_unit', to='masters.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Quotation_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='service.service_quotation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_quotation_items', to='masters.service')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_service', to='masters.service')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_items', to='service.service_order')),
            ],
        ),
        migrations.AddField(
            model_name='service_order',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='service.service_quotation'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='service_order_states', to='masters.state'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_transaction_type', to='masters.transaction_type'),
        ),
        migrations.AddField(
            model_name='service_order',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_unit', to='masters.unit'),
        ),
        migrations.CreateModel(
            name='Service_Invoice_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_invoice_service', to='masters.service')),
                ('service_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_invoice_items', to='service.service_invoice')),
            ],
        ),
        migrations.AddField(
            model_name='service_invoice',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_invoices', to='service.service_order'),
        ),
        migrations.AddField(
            model_name='service_invoice',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_invoice_transaction_type', to='masters.transaction_type'),
        ),
        migrations.AddField(
            model_name='service_invoice',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_invoice_unit', to='masters.unit'),
        ),
    ]
