# Generated by Django 4.2.15 on 2025-04-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_quotation',
            name='approved_by',
        ),
    ]
