# Generated by Django 4.2.15 on 2025-04-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_quotation_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_quotation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
