# Generated by Django 4.2.15 on 2025-04-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_quotation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_quotation_items',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
