# Generated by Django 4.2.15 on 2025-04-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0038_service_account_cost_center'),
        ('service', '0004_alter_service_quotation_items_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_quotation',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_currency', to='masters.currency'),
            preserve_default=False,
        ),
    ]
