# Generated by Django 4.2.15 on 2025-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_quotation_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_quotation',
            name='inr_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
