# Generated by Django 4.2.15 on 2025-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_service_quotation_items_inr_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_quotation',
            name='inr_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
