# Generated by Django 4.2.15 on 2025-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_service_quotation_inr_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_quotation',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_quotation',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service_quotation',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
