# Generated by Django 4.2.15 on 2025-05-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_service_quotation_payment_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_quotation',
            old_name='payment_terms',
            new_name='credit_terms',
        ),
        migrations.RemoveField(
            model_name='service_quotation',
            name='payment_due_date',
        ),
    ]
