# Generated by Django 4.2.15 on 2025-05-04 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0010_rename_payment_terms_service_quotation_credit_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_quotation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_service_supplier', to=settings.AUTH_USER_MODEL),
        ),
    ]
