# Generated by Django 4.2.15 on 2025-05-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0040_sub_cost_center'),
        ('service', '0011_alter_service_quotation_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_order',
            name='cost_center',
        ),
        migrations.AddField(
            model_name='service_order',
            name='sub_cost_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_cost_center', to='masters.sub_cost_center'),
            preserve_default=False,
        ),
    ]
