# Generated by Django 4.2.15 on 2025-05-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_service_order_amount_service_order_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_order',
            name='inr_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
