# Generated by Django 4.2.15 on 2025-05-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0041_supplier_profile_currency'),
        ('service', '0014_service_order_inr_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_order',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_currency', to='masters.currency'),
            preserve_default=False,
        ),
    ]
