# Generated by Django 4.2.15 on 2025-05-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_service_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_order',
            name='currency',
        ),
    ]
