# Generated by Django 4.2.15 on 2025-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_service_order_business_alter_service_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_order_items',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_order_items',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='service_order_items',
            name='completion_status',
            field=models.CharField(choices=[('WorkinProgress', 'WorkinProgress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='WorkinProgress', max_length=20),
        ),
        migrations.AlterField(
            model_name='service_invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
