# Generated by Django 4.2.15 on 2025-05-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_service_order_items_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_order_items',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
