# Generated by Django 4.2.15 on 2025-05-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_service_order_items_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_quotation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
