# Generated by Django 4.2.15 on 2025-05-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_alter_service_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_invoice',
            name='inr_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='service_invoice',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
