# Generated by Django 4.2.15 on 2025-06-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_service_invoice_items_cgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_invoice',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service_invoice',
            name='creditable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service_invoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service_invoice',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
