# Generated by Django 4.2.15 on 2025-06-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_service_invoice_cgst_service_invoice_creditable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_order_items',
            name='service_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_items_invoice', to='service.service_invoice'),
        ),
    ]
