# Generated by Django 4.2.15 on 2025-06-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_service_order_items_service_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_quotation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Closed', 'closed')], default='Pending', max_length=20),
        ),
    ]
