# Generated by Django 4.2.15 on 2025-06-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_alter_service_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_order',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_quotation', to='service.service_quotation'),
        ),
    ]
