# Generated by Django 4.2.15 on 2025-01-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_user_roles_department'),
        ('inventory', '0003_alter_purchase_order_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrn_items',
            old_name='excise_levies',
            new_name='excise_levies_export',
        ),
        migrations.AddField(
            model_name='mrn_items',
            name='excise_levies_import',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='quality_check',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.transaction_type'),
        ),
        migrations.AlterField(
            model_name='vehicle_unloading_report',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.transaction_type'),
        ),
    ]
