# Generated by Django 4.2.15 on 2025-04-06 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0030_alter_user_roles_department'),
        ('inventory', '0004_rename_excise_levies_mrn_items_excise_levies_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.service_contracts', verbose_name='Service_Rule'),
        ),
        migrations.CreateModel(
            name='Supplier_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('approved', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_approver', to=settings.AUTH_USER_MODEL)),
                ('transaction_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.transaction_type')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_Not_Vouchered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=30)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField()),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('approved', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_account', to='masters.account_chart')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_approver', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_supplier', to='masters.supplier')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.transaction_type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
    ]
