# Generated by Django 4.2.15 on 2025-04-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_quotation_inland_haulage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='inland_haulage',
        ),
    ]
