# Generated by Django 4.2.15 on 2025-04-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0034_accountingyear_city_unitaccountbalance'),
        ('inventory', '0007_remove_quotation_inland_haulage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.service_contracts', verbose_name='Clearance_Charges_Rule Only import transaction'),
        ),
    ]
