# Generated by Django 4.2.15 on 2025-04-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_purchase_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_items',
            name='balance_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
