# Generated by Django 4.2.15 on 2025-06-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_purchase_order_items_balance_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax_table',
            old_name='section',
            new_name='tds_section',
        ),
        migrations.AddField(
            model_name='receipt_not_vouchered',
            name='matching_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt_not_vouchered',
            name='provision_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tax_table',
            name='gstr2b_status',
            field=models.BooleanField(default=False, help_text='Pls. Tick if this  matches with GSTR-2B'),
        ),
        migrations.AddField(
            model_name='tax_table',
            name='gstr3b_status',
            field=models.BooleanField(default=False, help_text='Pls. Tick if this  matches with GSTR-3B'),
        ),
        migrations.AddField(
            model_name='tax_table',
            name='matching_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tax_table',
            name='tcs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
