# Generated by Django 4.2.15 on 2025-06-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_section_tax_table_tds_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='quality_approval',
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='cgst_freight',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='cst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='custom_clearance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='custom_duty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='excise_levies_export',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='excise_levies_import',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='igst_freight',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='landed_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='sgst_freight',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=30),
        ),
        migrations.AddField(
            model_name='material_receipt_note',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt_not_vouchered',
            name='mrn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_mrn', to='inventory.material_receipt_note'),
        ),
    ]
