# Generated by Django 4.2.15 on 2025-06-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_material_receipt_note_quality_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='cgst_freight',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='cst',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='custom_clearance',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='custom_duty',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='excise_levies_export',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='excise_levies_import',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='igst_freight',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='landed_cost',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='sgst_freight',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='value',
        ),
        migrations.RemoveField(
            model_name='material_receipt_note',
            name='vat',
        ),
        migrations.AlterField(
            model_name='receipt_not_vouchered',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receipt_not_vouchered',
            name='mrn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_not_vouchered_mrn', to='inventory.material_receipt_note'),
        ),
    ]
