# Generated by Django 4.2.15 on 2025-06-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0051_freight_transporter'),
        ('inventory', '0012_remove_material_receipt_note_cgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_not_vouchered',
            name='tax_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_tax_account', to='masters.account_chart'),
        ),
        migrations.AlterField(
            model_name='mrn_items',
            name='cgst_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mrn_items',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mrn_items',
            name='igst_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mrn_items',
            name='sgst_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplier_invoice',
            name='invoice_date',
            field=models.DateField(),
        ),
    ]
