# Generated by Django 4.2.15 on 2025-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_receipt_not_vouchered_tax_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_not_vouchered',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='receipt_not_vouchered',
            name='voucher_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Freight', 'Freight'), ('Service', 'Service')], default='Purchase', help_text='Pls. Select the type of voucher', max_length=20),
        ),
    ]
