# Generated by Django 4.2.15 on 2025-06-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_receipt_not_vouchered_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrn_items',
            name='freight_match',
            field=models.BooleanField(default=False, help_text='Pls. Tick if this item is matched with freight invoice'),
        ),
        migrations.AddField(
            model_name='mrn_items',
            name='supplier_match',
            field=models.BooleanField(default=False, help_text='Pls. Tick if this item is matched with supplier invoice'),
        ),
    ]
