# Generated by Django 4.2.15 on 2025-06-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_mrn_items_freight_match_mrn_items_supplier_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_invoice',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='cst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='gstr1_status',
            field=models.BooleanField(default=False, help_text='Pls. Tick if this  matches with GSTR-1'),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='gstr2b_status',
            field=models.BooleanField(default=False, help_text='Pls. Tick if this  matches with GSTR-2B'),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='gstr3b_status',
            field=models.BooleanField(default=False, help_text='Pls. Tick if this  matches with GSTR-3B'),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='nature_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
