# Generated by Django 4.2.15 on 2025-07-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_supplier_invoice_cgst_supplier_invoice_cst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_invoice',
            name='aggregate_invoice_Value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
