# Generated by Django 4.2.15 on 2025-07-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0052_supplier_profile_is_sez_supplier_profile_supply_type'),
        ('inventory', '0017_supplier_invoice_aggregate_invoice_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_invoice',
            name='supllier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoice', to='masters.supplier'),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
