# Generated by Django 4.2.15 on 2025-07-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_supplier_invoice_supllier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_invoice',
            old_name='supllier',
            new_name='supplier',
        ),
    ]
