# Generated by Django 4.2.15 on 2025-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_rename_supllier_supplier_invoice_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_invoice',
            name='tds_194q',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
