# Generated by Django 4.2.15 on 2025-07-01 16:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0020_supplier_invoice_tds_194q'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_invoice',
            name='aggregate_tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='gross_invoice_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 1, 16, 39, 15, 545653)),
            preserve_default=False,
        ),
    ]
