# Generated by Django 4.2.15 on 2025-07-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_supplier_invoice_aggregate_tds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_invoice',
            old_name='aggregate_invoice_Value',
            new_name='aggregate_invoice_value',
        ),
    ]
