# Generated by Django 4.2.15 on 2025-07-01 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_rename_aggregate_invoice_value_supplier_invoice_aggregate_invoice_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_invoice',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 1, 16, 58, 59, 979285)),
            preserve_default=False,
        ),
    ]
