# Generated by Django 4.2.15 on 2025-07-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_supplier_invoice_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_invoice',
            name='cgst_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='igst_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='supplier_invoice',
            name='sgst_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
