# Generated by Django 4.2.15 on 2025-07-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_supplier_invoice_cgst_freight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrn_items',
            name='mrn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.material_receipt_note'),
        ),
    ]
