# Generated by Django 4.2.15 on 2025-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_mrn_items_mrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_invoice',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
