# Generated by Django 4.2.15 on 2025-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_supplier_invoice_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_invoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Pls. Enter the due date for payment', null=True),
        ),
    ]
