# Generated by Django 4.2.15 on 2025-03-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0011_customer_state_excise_levies_rate_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edp', models.FloatField(verbose_name='Ex-Distillery_Price')),
                ('mop', models.FloatField(blank=True, null=True, verbose_name='Market Operting Rate')),
                ('msp', models.FloatField(blank=True, null=True, verbose_name='Minimum Sale Price')),
                ('mrp', models.FloatField(blank=True, null=True, verbose_name='Maximum Retail Price')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='masters.sku')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.state')),
            ],
            options={
                'unique_together': {('state', 'brand', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_no', models.CharField(max_length=50, unique=True)),
                ('permit_date', models.DateField()),
                ('valid_till', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Permit_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_permit', to='sale.permit')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_item', to='masters.item')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_sku', to='masters.sku')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_uom', to='masters.unit_of_measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('is_pending', models.BooleanField(default=True)),
                ('order_remarks', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_created_by', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_permit', to='sale.permit')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_transaction_type', to='masters.transaction_type')),
            ],
        ),
        migrations.CreateModel(
            name='Slabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=0)),
                ('levy_rate', models.FloatField()),
                ('levy_formula', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('levy_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.state_excise_levies')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.state')),
                ('uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.unit_of_measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('excise_duty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bottling_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('export_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outward_freight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_brand', to='masters.brand')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='sale.permit_item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='sale.sales_order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sku', to='masters.sku')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Invoice_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('excise_duty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bottling_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('export_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outward_freight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_brand', to='masters.brand')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_invoice', to='sale.sales_invoice')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item', to='sale.sales_order_item')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sku', to='masters.sku')),
            ],
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoice_order', to='sale.sales_order'),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoice_transaction_type', to='masters.transaction_type'),
        ),
        migrations.CreateModel(
            name='Cost_Card_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levy_name', models.CharField(max_length=50)),
                ('levy_rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('levy_unit', models.CharField(max_length=20)),
                ('levy_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateField()),
                ('valid_till', models.DateField()),
                ('payee', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cost_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.cost_card')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
