# Generated by Django 4.2.15 on 2025-03-13 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0011_customer_state_excise_levies_rate_customer_profile'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outward_Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_qty', models.IntegerField(default=0)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('freight', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='or_created_by', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_freight_supplier', to='masters.supplier')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='or_unit', to='masters.unit')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.vehicle_type')),
            ],
        ),
        migrations.AddField(
            model_name='sales_order',
            name='freight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_freight', to='sale.outward_freight'),
        ),
    ]
