# Generated by Django 4.2.15 on 2025-03-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_state_excise_levies_rate_levy_formula'),
        ('sale', '0002_outward_freight_sales_order_freight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slabs',
            name='levy_formula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slab_formaula', to='masters.formula'),
            preserve_default=False,
        ),
    ]
