# Generated by Django 4.2.15 on 2025-03-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_slabs_levy_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_card',
            name='edp',
            field=models.FloatField(verbose_name='Ex-Distillery_Price per Case'),
        ),
        migrations.AlterField(
            model_name='cost_card',
            name='mop',
            field=models.FloatField(blank=True, null=True, verbose_name='Market Operting Rate Per Case'),
        ),
        migrations.AlterField(
            model_name='cost_card',
            name='mrp',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum Retail Price Per Case'),
        ),
        migrations.AlterField(
            model_name='cost_card',
            name='msp',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Sale Price Per Case'),
        ),
    ]
