# Generated by Django 4.2.15 on 2025-03-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_cost_card_edp_alter_cost_card_mop_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cost_card',
            unique_together=set(),
        ),
    ]
