# Generated by Django 4.2.15 on 2025-03-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_delete_subtotal'),
        ('sale', '0005_alter_cost_card_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_card',
            name='valid_from',
            field=models.DateField(default='2024-04-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cost_card',
            name='valid_till',
            field=models.DateField(default='2025-03-31'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cost_card',
            unique_together={('state', 'brand', 'sku')},
        ),
    ]
