# Generated by Django 4.2.15 on 2025-03-25 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0007_alter_cost_card_unique_together_permit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='permit_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permit',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_no',
            field=models.CharField(choices=[('pending_order', '100'), ('order_made', '200'), ('executed', '300')], max_length=50, unique=True),
        ),
    ]
