# Generated by Django 4.2.15 on 2025-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_permit_created_permit_created_by_permit_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='permit_no',
        ),
        migrations.AddField(
            model_name='permit',
            name='permit_number',
            field=models.CharField(choices=[('pending_order', '100'), ('order_made', '200'), ('executed', '300')], default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
