# Generated by Django 4.2.15 on 2025-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_remove_permit_permit_no_permit_permit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('100', 'pending_order'), ('200', 'order_made'), ('300', 'executed')], default='100', max_length=50),
        ),
    ]
