# Generated by Django 4.2.15 on 2025-03-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_customer_account'),
        ('sale', '0010_alter_permit_permit_number_alter_permit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit_item',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permit_brand', to='masters.brand'),
            preserve_default=False,
        ),
    ]
