# Generated by Django 4.2.15 on 2025-03-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_permit_item_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_invoice',
            name='order',
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='permit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoice_permit', to='sale.permit'),
            preserve_default=False,
        ),
    ]
