# Generated by Django 4.2.15 on 2025-03-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_remove_sales_invoice_order_sales_invoice_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_invoice_item',
            name='invoice_amount',
        ),
        migrations.RemoveField(
            model_name='sales_invoice_item',
            name='per_unit_price',
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='total_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='sales_invoice_item',
            name='basic_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales_invoice_item',
            name='bottling_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales_invoice_item',
            name='excise_duty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales_invoice_item',
            name='export_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales_invoice_item',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales_invoice_item',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales_invoice_item',
            name='outward_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
