# Generated by Django 4.2.15 on 2025-03-29 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0027_state_excise_levies_rate_account'),
        ('sale', '0013_remove_sales_invoice_item_invoice_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_invoice_item',
            name='bottling_fee',
        ),
        migrations.RemoveField(
            model_name='sales_invoice_item',
            name='excise_duty',
        ),
        migrations.RemoveField(
            model_name='sales_invoice_item',
            name='export_fee',
        ),
        migrations.RemoveField(
            model_name='sales_invoice_item',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='sales_invoice_item',
            name='other_charges',
        ),
        migrations.RemoveField(
            model_name='sales_invoice_item',
            name='outward_freight',
        ),
        migrations.AddField(
            model_name='sales_invoice_item',
            name='levies_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sales_invoice_item',
            name='basic_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.CreateModel(
            name='Sale_Invoice_Levies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_levy_lines', to='sale.sales_invoice_item')),
                ('levy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_levy_name', to='masters.state_excise_levies_rate')),
            ],
        ),
    ]
