# Generated by Django 4.2.15 on 2025-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0014_remove_sales_invoice_item_bottling_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='basic_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='levies_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='tcs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
