# Generated by Django 4.2.15 on 2025-03-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_tcs_head_tcs'),
        ('sale', '0015_sales_invoice_basic_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoice_unit', to='masters.unit'),
            preserve_default=False,
        ),
    ]
