# Generated by Django 4.2.15 on 2025-03-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0016_sales_invoice_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice_item',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item', to='sale.permit_item'),
        ),
    ]
