# Generated by Django 4.2.15 on 2025-03-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0017_alter_sales_invoice_item_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_invoice_item',
            name='total_invoice_amount',
        ),
    ]
