# Generated by Django 4.2.15 on 2025-03-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0018_remove_sales_invoice_item_total_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_invoice_levies',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_levy', to='sale.sales_invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale_invoice_levies',
            name='invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_levy_lines', to='sale.sales_invoice_item'),
        ),
    ]
