# Generated by Django 4.2.15 on 2025-03-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0019_sale_invoice_levies_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_order_item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sales_order_item',
            name='product_item',
        ),
        migrations.RemoveField(
            model_name='sales_order_item',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='sales_order_item',
            name='sku',
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Sales_Order',
        ),
        migrations.DeleteModel(
            name='Sales_Order_Item',
        ),
    ]
