# Generated by Django 4.2.15 on 2025-03-30 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0029_alter_vehicle_type_unit_of_measurement'),
        ('sale', '0020_remove_sales_order_item_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_For_Loading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=30)),
                ('entry_date', models.DateTimeField()),
                ('vehicle_number', models.CharField(max_length=20)),
                ('material', models.CharField(choices=[('Liquor', 'Liquor'), ('Scrap', 'Scrap'), ('Other', 'Other')], max_length=20)),
                ('driver_name', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('license_validity', models.DateField()),
                ('engine_number', models.CharField(max_length=50)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_truck_created_by', to=settings.AUTH_USER_MODEL)),
                ('licensing_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_truck_licensing_state', to='masters.state')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_truck_transaction_type', to='masters.transaction_type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_truck_unit', to='masters.unit')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_truck_vehicle_type', to='masters.vehicle_type')),
            ],
        ),
    ]
