# Generated by Django 4.2.15 on 2025-03-31 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0021_vehicle_for_loading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='excise_pass',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='excise_pass_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='lr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='lr_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='truck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoice_truck', to='sale.vehicle_for_loading'),
            preserve_default=False,
        ),
    ]
