# Generated by Django 4.2.15 on 2025-04-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0022_sales_invoice_excise_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='lr_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lorry Receipt Date'),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='lr_number',
            field=models.CharField(default='', max_length=50, verbose_name='Lorry Receipt  Number'),
        ),
    ]
